const AchievementActionTypes = {
  CREATE_ACHIEVEMENT_START: 'CREATE_ACHIEVEMENT_START',
  CREATE_ACHIEVEMENT_END: 'CREATE_ACHIEVEMENT_END',
  CREATE_ACHIEVEMENT_ERROR: 'CREATE_ACHIEVEMENT_ERROR',
  GET_ACHIEVEMENTS_START: 'GET_ACHIEVEMENTS_START',
  GET_ACHIEVEMENTS_ERROR: 'GET_ACHIEVEMENTS_ERROR',
  GET_ACHIEVEMENTS_END: 'GET_ACHIEVEMENTS_END'
}

export default AchievementActionTypes