const PostActionTypes = {
  CREATE_POST_START: 'CREATE_POST_START',
  CREATE_POST_END: 'CREATE_POST_END',
  CREATE_POST_ERROR: 'CREATE_POST_ERROR',
  GET_POSTS_START: 'GET_POSTS_START',
  GET_POSTS_ERROR: 'GET_POSTS_ERROR',
  GET_POSTS_END: 'GET_POSTS_END'
}

export default PostActionTypes