const PortfolioActionTypes = {
  CREATE_PORTFOLIO_START: 'CREATE_PORTFOLIO_START',
  CREATE_PORTFOLIO_END: 'CREATE_PORTFOLIO_END',
  CREATE_PORTFOLIO_ERROR: 'CREATE_PORTFOLIO_ERROR',
  GET_PORTFOLIO_START: 'GET_PORTFOLIO_START',
  GET_PORTFOLIO_ERROR: 'GET_PORTFOLIO_ERROR',
  GET_PORTFOLIO_END: 'GET_PORTFOLIO_END'
}

export default PortfolioActionTypes