const SkillActionTypes = {
  CREATE_SKILL_START: 'CREATE_SKILL_START',
  CREATE_SKILL_END: 'CREATE_SKILL_END',
  CREATE_SKILL_ERROR: 'CREATE_SKILL_ERROR',
  GET_SKILLS_START: 'GET_SKILLS_START',
  GET_SKILLS_ERROR: 'GET_SKILLS_ERROR',
  GET_SKILLS_END: 'GET_SKILLS_END'
}

export default SkillActionTypes